### ISSUE TITLE
Blockサイズの調整

### ISSUE THREAD

**Issue by xmba15** [bajsk/matchTemplateGpu#11]
- Blockサイズを変更し，結果を比較してみます．

**Comment by xmba15** [comment]
- CUDA: 21.1689 ms.
- CUDA(withStaticSharedMemory): 15.0406 ms.
- CUDA(withDynamicSharedMemory): 13.7289 ms.
- CUDA(withStaticSharedMemory_withLoopUnrolling): 12.9779 ms.
- CUDA(withDynamicSharedMemory_withLoopUnrolling): 12.9508 ms.
- CUDA(withDynamicSharedMemory_withLoopUnrolling_blockSize(128x1): 11.0902 ms.

**Comment by atinfinity** [comment]
#12 がマージされており、この施策適用前後の計測時間も記載されているので本issueはクローズとします。
