### ISSUE TITLE
発表の構成

### ISSUE THREAD

**Issue by xmba15** [bajsk/matchTemplateGpu#13]
発表構成をまずは章レベルでよいので列挙してみてください。

**Comment by xmba15** [comment]
- テンプレートマッチングのアルゴリズムについて説明
- CPUオンリの実装について説明
- GPUによる最適化：
  - Shared Memory
    - 静的
    - 動的
  - ループ展開
  - ブロックサイズの調整
  - リードオンリキャッシュの使用

**Comment by atinfinity** [comment]
@bajsk 
構成の大枠は提示してもらった感じでよいと思います。これらに加えて、今回の計測環境情報（PC、GPU、OS、開発環境等）やVisual Profilerでのプロファイリング結果、分析結果等も合わせて書いてもらえると。
あと、今回のテーマで学んだことや苦労したことなども前もって整理されているとよいと思います。

**Comment by atinfinity** [comment]
発表構成問題ないため、本件closeします。
