### ISSUE TITLE
readOnlyキャッシュ利用

### ISSUE THREAD

**Issue by xmba15** [bajsk/matchTemplateGpu#14]
- リードオンリキャッシュの使用でMemory Dependencyを削減する．
- Verifyで結果を確認した．

**Comment by xmba15** [comment]
- CUDA: 21.4373 ms.
- CUDA(withStaticSharedMemory): 13.7275 ms.
- CUDA(withDynamicSharedMemory): 13.7463 ms.
- CUDA(withStaticSharedMemory_withLoopUnrolling): 12.9872 ms.
- CUDA(withDynamicSharedMemory_withLoopUnrolling): 12.9556 ms.
- CUDA(withDynamicSharedMemory_withLoopUnrolling_blockSize(128x1): 11.0775 ms.
- CUDA(withDynamicSharedMemory_withLoopUnrolling_blockSize_readOnlyCache(128x1): 8.33203 ms.

**Comment by atinfinity** [comment]
情報追記ありがとうございました。#14 がマージされたので本issueはクローズします。
