### ISSUE TITLE
Shared Memoryの使用

### ISSUE THREAD

**Issue by xmba15** [bajsk/matchTemplateGpu#5]
- static shared memory と dynamic shared memoryを使用し，比較する．

**Comment by atinfinity** [comment]
shared memoryの静的確保については #4 で対応してもらったので、動的確保についても実装してPR投げてください！

**Comment by atinfinity** [comment]
#4、#7 がマージされたので本issueはクローズします。

**Comment by bajsk** [comment]
+ 実行の結果
　- CUDA: 21.5142 ms.
　- CUDA(withStaticSharedMemory): 14.8847 ms.
　- CUDA(withDynamicSharedMemory): 13.6859 ms

**Comment by xmba15** [comment]
- 実行の結果
  - CUDA: 21.2428 ms.
  - CUDA(withStaticSharedMemory): 13.6451 ms.
  - CUDA(withDynamicSharedMemory): 13.6435 ms
