### ISSUE TITLE
ループアンローリングの実装、計測を行う

### ISSUE THREAD

**Issue by atinfinity** [bajsk/matchTemplateGpu#9]
ループアンローリングの実装、計測を行い、計測時間追記お願いします。

**Comment by xmba15** [comment]
- 実行の結果
  - CUDA(withStaticSharedMemory): 13.6451 ms.
  - CUDA(withDynamicSharedMemory): 13.6435 ms.
  - CUDA(withStaticSharedMemory_withLoopUnrolling): 12.9383 ms.
  - CUDA(withDynamicSharedMemory_withLoopUnrolling): 12.9683 ms.

**Comment by atinfinity** [comment]
#10 がマージされたので本issueはクローズします。
